### ISSUE TITLE
Fill is not applied when using url(path) with resolve.alias

### ISSUE THREAD

**Issue by mzymta** [kisenka/svg-fill-loader#12]
Hi there,

The svg image doesn't get colored when using webpack alias as path, e.g.:
background-image: url("~my-folder/images/image.svg?fill=green");

Any ideas how I can get this working?

**Comment by kisenka** [comment]
It may be related to [webpack's enhanced resolve issue](https://github.com/webpack/webpack/issues/1289), but I need more information. Please create a github repo with reproducible behavious.

**Comment by mzymta** [comment]
Hi @kisenka, 
here is a test repo where this behavior was reproduced: [https://github.com/mzymta/svg-fill-loader-with-webpack-alias-path](url).

**Comment by kisenka** [comment]
@mzymta 
You have defined 2 loader rules for .svg extension - [line 11](https://github.com/mzymta/svg-fill-loader-with-webpack-alias-path/blob/master/webpack.config.js#L11) and [line 20](https://github.com/mzymta/svg-fill-loader-with-webpack-alias-path/blob/master/webpack.config.js#L20). But second rule will never applied because of wrong regexp - `/\.svg\?fill=/` (which was copied from readme I guess). Proper regexp for webpack 1 will be `/\.svg(\?fill=.*)?|$/`, for webpack 2 you can use default `/\.svg$/`. Readme was updated.

**Comment by kisenka** [comment]
@mzymta check my version - https://github.com/kisenka/svg-fill-loader-with-webpack-alias-path/commit/d488b01bbd495b6f4ea486b02b89b468dea13a65

**Comment by kisenka** [comment]
@mzymta fixed?

**Comment by mzymta** [comment]
Hi @kisenka. Thank you for the provided solution, but unfortunately I didn't have a chance to test it yet (my apologies)
I will try it out today and will let you know.
Thanks

**Comment by mzymta** [comment]
@kisenka, I made changes to webpack config as suggested but it didn't fix the issue. Please see 6ad063b7cc7f2b8d0350193a48ce2ae6c279144c
With the provided regex css stopped to be applied

**Comment by mzymta** [comment]
@kisenka, I made changes to webpack config as suggested but it didn't fix the issue. Please see [here](https://github.com/mzymta/svg-fill-loader-with-webpack-alias-path/commit/6ad063b7cc7f2b8d0350193a48ce2ae6c279144c)
With the provided regex css stopped to be applied.

**Comment by kisenka** [comment]
@mzymta which webpack version is used? 1?

**Comment by mzymta** [comment]
@kisenka, yes, first webpack (1.14.0)

**Comment by kisenka** [comment]
@mzymta first of all it was my fault because regexp should be `/\.svg((\?.*)?|$)/`. 
But seems like webpack bug with aliased loader still exists (see [#1513](https://github.com/webpack/webpack/issues/1513) and [#3320](https://github.com/webpack/webpack/issues/3320)), so I published svg-fill-loader 0.0.8 version with workaround, please update and recheck.
