### ISSUE TITLE
Doesn't work with vuejs-templates/webpack

### ISSUE THREAD

**Issue by nerdyglasses** [kisenka/svg-fill-loader#4]
I'm trying to get that working for a couple of hours now.
Unfortunately I'm not enough experienced with webpack to solve that.

That's the complete project
https://github.com/vuejs-templates/webpack

That's the webpack config
https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js

I've changed the loaders object to this:

``` javscript
{
  test: /\.(png|jpe?g|gif)(\?.*)?$/,
  loader: 'url',
  query: {
    limit: 10000,
    name: utils.assetsPath('img/[name].[hash:7].[ext]')
  }
},
{
  test: /\.svg(\?.*)?$/, // match only imports like `url(image.svg?fill=red)`
  loaders: [
    'url', // or file-loader
    'svg-fill' // `selector` option will be used for all images processed by loader
  ]
}
```

in your library `this.resourceQuery` is always `null` even though I'm adding `?fill=red` to the svg paths

Do you have an idea how to make it work?

**Comment by kisenka** [comment]
@nerdyglasses which webpack version is used?

**Comment by nerdyglasses** [comment]
@kisenka `webpack@^1.13.2`

**Comment by kisenka** [comment]
@nerdyglasses wait here, investigation in progress

**Comment by nerdyglasses** [comment]
@kisenka thx. I'm also on gitter. Pinged you there.

**Comment by kisenka** [comment]
@nerdyglasses could you please provide code which not works? For me following works as expected:

**App.vue**
```html
<template>
  <div id="app">
    <img src="./1.svg?fill=red">
    <hello></hello>
  </div>
</template>
```

**Comment by nerdyglasses** [comment]
@kisenka I've added a test here:
https://github.com/nerdyglasses/vue-webpack-svg-fill-loader-test

I have invited you as a collaborator.

**Comment by clehnert-psl** [comment]
@nerdyglasses, I was able to get this to work in your test. However, this is meant to change the fill for svg images used as background images in CSS. What I see in your test is an svg asset applied as an `<img>` `src` attribute. Additionally, the svg you included is made up of strokes with a black color. Even if you set this svg as the `background: url()`, it won't accept the color you apply with svg-fill.

Also, this part in your webpack config is hijacking the load of svg assets—preventing svg-fill from loading them:
`test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,`
This will cause all svgs to be loaded with _this_ loader instead of svg-fill.

**Comment by nerdyglasses** [comment]
@clehnert-psl thx man!
