### ISSUE TITLE
Incorrect Sass source mapping

### ISSUE THREAD

**Issue by CLL80** [kisenka/svg-fill-loader#7]
I'm using the svg-fill-loader in a webpack project started with the React Redux starter kit. Without the svg-fill-loader, my sourcemaps are working correctly, but with it, the line numbers and files are incorrect for some elements. [Here is a sample project to demostrate the issue](https://github.com/CLL80/sass-svg-fill-loader-test). For example, in this project, if you run `npm run dev` and inspect the "SVG fill loader with sourcemapping test" heading element. You will see this in the styles inspector:

```
.Header__font-theme___1CaSs, .Header__heading___1oL8z {
    font-family: Arial, sans-serif;
}
```

with `_font-theme.scss:1`, which is where the styling for this particular element originates from.

Unfortunately, when including the svg-fill-loader in the sass/scss loaders, the source mapping will not be correct for all elements.

Here is the sass/scss loader:
```
webpackConfig.module.loaders.push({
  test: /\.scss$|sass$/,
  loaders: [
    'style-loader',
    cssModulesLoader,
    'resolve-url-loader',
    'svg-fill-loader/encodeSharp',
    'sass-loader?sourceMap'
  ]
})
```

In the example project, the svg-fill-loader is commented out on line 161 of `config/webpack.config.js`. When uncommenting it and inspecting the same element, you can see the same class showing a map to `Header.scss:9`, which is incorrect.

I'm having this issue in a larger project, so I made this test project as an example to isolate and demonstrate this issue.

**Comment by kisenka** [comment]
Hey @CLL80!
Thanks for reporting. It was bug with encodeSharp loader, please update svg-fill-loader to 0.0.7.

Also you need to add option `keepQuery` to [resolve-url-loader](https://github.com/bholloway/resolve-url-loader/blob/d47374c9e1d5eb52f0d89b1a2cb6f3bb232f8cff/index.js#L47), because it removes query string by default (and it's strange).

Also it's safe to pass all SVGs through loader, if no fill param presented it just returns original source, so your SVG loaders configuration can be simplified to:

```js
{
  test: /\.svg($|\?fill=)/, 
  loaders: [
    'svg-url-loader',
    'svg-fill-loader'
  ],
  exclude: [/styles\/fonts/]
}
```

**Comment by CLL80** [comment]
Yes, this is working perfectly now. Thanks a lot!
